### ISSUE TITLE
Add Code Sample - Bootstrap Dropdowns

### ISSUE THREAD

**Issue by Bachittarjeet** [Banglorians/Web-Development#10]
It would be a great help if you can add new Lectures (Separate by Topic name = Folder Name)

Feel free to contact @Bachittarjeet for further details

**Comment by Abhishekchauhan089** [comment]
@Bachittarjeet I would like to work on this project

**Comment by Bachittarjeet** [comment]
Sure @Abhishekchauhan089 . Assigned to you

**Comment by Abhishekchauhan089** [comment]
okay @Bachittarjeet working on this issue...i will get the work done soon

**Comment by Bachittarjeet** [comment]
Sure
