### ISSUE TITLE
Add Code Sample - Bootstrap Jumbotron

### ISSUE THREAD

**Issue by Bachittarjeet** [Banglorians/Web-Development#13]
It would be a great help if you can add new Lectures (Separate by Topic name = Folder Name)

Feel free to contact @Bachittarjeet for further details

**Comment by akshitkumar450** [comment]
please assign this to me,,i would like to work on it..

**Comment by trivedidhruvil9** [comment]
Hi,
i have already code the sample code for bootstrap_jumbotron.
Here is the screen shot of the output.

let me know, if you need some changes!

![Screenshot (73)](https://user-images.githubusercontent.com/56179904/94985257-b110a200-0572-11eb-9b92-4c99c71a5ecb.png)

**Comment by Bachittarjeet** [comment]
Thanks @trivedidhruvil9 trivedidhruvil9
