### ISSUE TITLE
Add Code Sample - Bootstrap Modal

### ISSUE THREAD

**Issue by Bachittarjeet** [Banglorians/Web-Development#16]
It would be a great help if you can add new Lectures (Separate by Topic name = Folder Name)

Feel free to contact @Bachittarjeet for further details

**Comment by bratinkundu** [comment]
Hey @Bachittarjeet 
I have made a PR for this issue. Please review it and merge. Thanks!

**Comment by Bachittarjeet** [comment]
Thanks @bratinkundu
