### ISSUE TITLE
 Add Code Sample - Bootstrap Cards

### ISSUE THREAD

**Issue by Bachittarjeet** [Banglorians/Web-Development#8]
It would be a great help if you can add new Lectures (Separate by Topic name = Folder Name)

Feel free to contact @Bachittarjeet for further details

**Comment by thedevhaider** [comment]
@Bachittarjeet I have added one example for Bootstrap Card. I have raised one PR for the same. Could you please review it and merge it. Thanks in Advance!

**Comment by Bachittarjeet** [comment]
Thank you it was a great help :)
